/*
	Professor:	Daniel Silveira
	Módulo   :	Curso de SQL Server – Construindo um Banco de Dados  
	Aula 03  :  Criando o banco de dados com vários arquivos 

*/


--Seleciona o banco de dados Master
use master
go

-----
--Cria um banco de dados 
-----


CREATE DATABASE VENDAS
ON
(
	NAME = VENDAS, --NOME LÓGICO
	FILENAME = N'C:\SQL\VENDAS.MDF', --NOME FÍSICO
	SIZE = 10MB, -- KB, TB,GB TAMNHO INICIAL
	MAXSIZE = 100MB, -- TAMANHO MÁXIMO
	FILEGROWTH = 10MB -- CRESCIMENTO DO BANCO DE DADOS
),
(
	NAME = VENDAS_CADASTROS, --LOME LÓGICO
	FILENAME = N'C:\SQL\VENDAS_CADASTROS.MDF', --NOME FÍSICO
	SIZE = 10MB, -- KB, TB,GB TAMNHO INICIAL
	MAXSIZE = 100MB, -- TAMANHO MÁXIMO
	FILEGROWTH = 10MB -- CRESCIMENTO DO BANCO DE DADOS
)
LOG ON --Adiciona os arquivos de LOG
(	NAME = VENDAS_LOG,
	FILENAME = N'C:\SQL\VENDAS_LOG.LDF',
	SIZE = 10MB,
	MAXSIZE = 25MB,
	FILEGROWTH = 5MB
	),
(	NAME = VENDAS_CADASTROS_LOG,
	FILENAME = N'C:\SQL\VENDAS_CADASTROS_LOG.LDF',
	SIZE = 10MB,
	MAXSIZE = 25MB,
	FILEGROWTH = 5MB
	)	

----
--ALTERAR O ARQUIVO DO BANCO DE DADOS
-----
ALTER DATABASE VENDAS
MODIFY FILE 
(
	NAME = VENDAS, --LOME LÓGICO
	FILENAME = N'C:\SQL\BANCODEDADOS_VENDAS.MDF', --NOME FÍSICO
	SIZE = 16MB, -- KB, TB,GB TAMNHO INICIAL
	MAXSIZE = UNLIMITED, -- TAMANHO MÁXIMO
	FILEGROWTH = 10MB -- CRESCIMENTO DO BANCO DE DADOS
)
